# Render部署配置文件
services:
  - type: web
    name: little-writers-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: CLAUDE_API_KEY
        sync: false  # 需要手动设置
      - key: CLAUDE_API_HOST
        value: api.gptgod.online
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///little_writers.db
    healthCheckPath: /
